Repository edgexfoundry/blackbox-testing, pull requests merged in 2019-11, with the labels that each got.

#319 Update kong image to a current supported CentOS image (master)
  bin/env.sh
  docker-compose.yml
Labels: bug, fuji

#321 Update support-rulesengine to newest version (fuji)
  bin/arm64_env.sh
  bin/env.sh
Labels: fuji

#316 Removed references to Mongo in prerequisites.
  docs/How-to-run-blackbox-testing.rst
Labels: geneva
